#!/bin/sh
# wrapper for wslview+wslpath
if [ -z "${1#file://*}" ];then
    #echo "file _$@_" > ~/tmp/test.txt
    wslview "$(wslpath -w "$(echo $1 | sed -E 's|^file://||')")"
else
    #echo "other _$@_" > ~/tmp/test.txt
    wslview "$1"
fi
